### ISSUE TITLE
code 137

### ISSUE THREAD

**Issue by AndrijaRD** [digitallyinduced/ihp-chat-example-app#7]
After running it on linux(debian) i got this error:

/nix/store/43215b010yhnvpmr169abg324zq1l0sr-stdenv-linux/setup: line 1389:   320 Killed                  ./Setup build
error: builder for '/nix/store/62hsa0j7ai2k6p3mh9m97cqj7vprjvlf-ormolu-0.5.0.0.drv' failed with exit code 137
error: 1 dependencies of derivation '/nix/store/1w66qrx0qh21hnqc2v16b8xxfcj7qqxx-ghc-9.2.4-with-packages.drv' failed to build
direnv: loading /opt/ihp-chat-example-app/.envrc
./start: line 29: RunDevServer: command not found

![image](https://user-images.githubusercontent.com/55910028/227730539-91d24ce9-2ffd-4163-8a54-f185aebd6a68.png)

**Comment by mpscholten** [comment]
Can you run the auto troubleshooting https://ihp.digitallyinduced.com/Guide/troubleshooting.html ?

**Comment by AndrijaRD** [comment]
> Can you run the auto troubleshooting https://ihp.digitallyinduced.com/Guide/troubleshooting.html ?

yea, i got this: 

Checking that the current directory is an IHP project:
+ Found Main.hs
+ Found start script
+ Nix installed
Checking direnv:
+ Found .envrc
+ direnv loads .envrc
- direnv denied .envrc, run `direnv allow` to allow .envrc
- ghci is not loaded from /nix/store/... Is direnv hooked into your shell?
Checking .ghci:
+ Found .ghci
Traceback (most recent call last):
  File "<stdin>", line 159, in <module>
  File "<stdin>", line 66, in run_command
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ghci'

![image](https://user-images.githubusercontent.com/55910028/227737579-fbbe9514-8b9a-4fc3-ac19-63574f1d0031.png)

**Comment by AndrijaRD** [comment]
i also tried using:

nix-shell --run 'make build/ihp-lib'

insted of just ./start

and after 2h i got this:

error: builder for '/nix/store/ygq7jdmf2lp6bamc01395c95rfjajxwz-ihp-v0.20.0.drv' failed with exit code 137
error: 1 dependencies of derivation '/nix/store/1w66qrx0qh21hnqc2v16b8xxfcj7qqxx-ghc-9.2.4-with-packages.drv' failed to build

![image](https://user-images.githubusercontent.com/55910028/227737652-b0f306bf-d0e0-4035-b249-ea8b96d5ec05.png)

**Comment by mpscholten** [comment]
To me it seems that cachix is not installed and everything is compiled from scratch because of that. The exit code 137 could be an out of memory error.

Can you run ` nix-env -iA cachix -f https://cachix.org/api/v1/install` to install cachix and then use `cachix use digitallyinduced` to use the IHP binary cache? After that the build should go a lot faster and not take huge amounts of memory, which should fix the problem.

**Comment by AndrijaRD** [comment]
ok have runed it and i got:

Configured https://digitallyinduced.cachix.org binary cache in /home/username/.config/nix/nix.conf

I have run it using ./start

And it worked. Thanks!

**Comment by mpscholten** [comment]
Great, happy to hear it's working now 👍
